-- First, delete any existing questions for course_id=3 and week=1
DELETE FROM quiz_questions 
WHERE course_id = '3' AND week = '1';

-- Now insert the new questions
INSERT INTO quiz_questions (question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty, order_number, course_id, week) VALUES
  -- Standard Questions (1-8)
  ('What does a confusion matrix help evaluate?',
   'Model architecture',
   'Classification performance',
   'Hyperparameter tuning',
   'Dataset size',
   'b',
   'standard', 1, '3', '1'),

  ('Which algorithm is commonly used for classification?',
   'K-Means',
   'Linear Regression',
   'Support Vector Machine',
   'Apriori',
   'c',
   'standard', 2, '3', '1'),

  ('What does "epoch" mean in training?',
   'One full pass through the entire dataset',
   'A random sample of data',
   'A model checkpoint',
   'A learning rate schedule',
   'a',
   'standard', 3, '3', '1'),

  ('In machine learning, what does "generalization" mean?',
   'Model memorizes data',
   'Model performs well on unseen data',
   'Model runs faster',
   'Model reduces parameter count',
   'b',
   'standard', 4, '3', '1'),

  ('Which algorithm is MOST suitable for dimensionality reduction?',
   'PCA',
   'Naive Bayes',
   'Decision Tree',
   'Random Forest',
   'a',
   'standard', 5, '3', '1'),

  ('Which metric is best for highly imbalanced datasets?',
   'Accuracy',
   'F1 Score',
   'Loss',
   'Gradient',
   'b',
   'standard', 6, '3', '1'),

  ('Which model is best for sequence-based input (like text)?',
   'CNN',
   'RNN',
   'Decision Tree',
   'KNN',
   'b',
   'standard', 7, '3', '1'),

  ('What does dropout prevent?',
   'Data scaling',
   'Overfitting',
   'Underfitting',
   'Feature extraction',
   'b',
   'standard', 8, '3', '1'),

  -- Boss Questions (9-15)
  ('Which of the following is NOT a benefit of using batch gradient descent?',
   'Stable convergence',
   'Works well with large datasets',
   'Can get stuck in local minima',
   'Less noisy updates',
   'b',
   'boss', 9, '3', '1'),

  ('Which option is NOT a type of neural network?',
   'CNN',
   'RNN',
   'GAN',
   'PHP Network',
   'd',
   'boss', 10, '3', '1'),

  ('Which of the following is NOT a cause of underfitting?',
   'Too simple model',
   'Too little training',
   'High bias',
   'Too many parameters',
   'd',
   'boss', 11, '3', '1'),

  ('Which is NOT a commonly used optimizer in deep learning?',
   'Adam',
   'RMSProp',
   'SGD',
   'BlueBoost Optimizer',
   'd',
   'boss', 12, '3', '1'),

  ('Which of the following is NOT a challenge in reinforcement learning?',
   'Delayed rewards',
   'Exploration vs exploitation',
   'Large state space',
   'Pre-trained embeddings',
   'd',
   'boss', 13, '3', '1'),

  ('Which is NOT a property of decision trees?',
   'Easy to interpret',
   'Sensitive to noisy data',
   'Require scaling of features',
   'Can handle non-linear relationships',
   'c',
   'boss', 14, '3', '1'),

  ('Which option is NOT true about CNNs?',
   'They use filters/kernels',
   'They reduce spatial dimensions through pooling',
   'They are commonly used for tabular data',
   'They extract patterns from images',
   'c',
   'boss', 15, '3', '1');